version: "3.9"

services:
  backend:
    build: .
    container_name: drugsback-backend
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - BASE_PATH=/drugsback
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: drugsback-redis
    restart: unless-stopped

  celery:
    build: .
    container_name: drugsback-celery
    command: celery -A backend.celery_app worker --loglevel=info
    depends_on:
      - backend
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
